In [1]:
import duckdb

In [2]:
con = duckdb.connect('../change_tracker.db')

In [ ]:
drivers_average_score_data = con.sql(f"""                        
                        WITH latest_answers AS (
                            SELECT
                                q.id AS question_id,
                                d.drivers_name,
                                CAST(a.answers AS INTEGER) AS answers
                            FROM answers a
                            JOIN users u      ON u.id = a.user_id
                            JOIN questions q  ON q.id = a.questions_id
                            JOIN drivers d    ON d.id = q.drivers_id
                            QUALIFY ROW_NUMBER() OVER (
                                PARTITION BY q.id
                                ORDER BY a.modified_time DESC, a.id DESC
                            ) = 1
                        )
                        SELECT
                            drivers_name,
                            ROUND((SUM(answers) * 1.0 / COUNT(question_id)) / 7 * 100, 2) AS average_answer_percentage
                        FROM latest_answers
                        GROUP BY drivers_name;
                        """).fetchall()

drivers_question_data = con.sql(
                        f"""
                        WITH latest_answers AS (    
                            SELECT
                                q.id AS question_id,
                                d.drivers_name,
                                q.qcode,
                                CAST(a.answers AS INTEGER) AS answers
                            FROM answers a
                                JOIN users u      ON u.id = a.user_id
                                JOIN questions q  ON q.id = a.questions_id
                                JOIN drivers d    ON d.id = q.drivers_id
                                QUALIFY ROW_NUMBER() OVER (
                                PARTITION BY q.id
                                ORDER BY a.modified_time DESC, a.id DESC
                            ) = 1
                        )
                        SELECT
                            drivers_name,
                            qcode,
                            ROUND((SUM(answers) * 1.0 / COUNT(question_id)) / 7 * 100, 2) AS average_answer_percentage
                        FROM latest_answers
                        GROUP BY drivers_name, qcode ;
                        """
                        ).fetchall()

In [11]:
dict(drivers_average_score_data)

{'Business Performance': 42.86,
 'Team Leadership': 57.14,
 'Fear & Frustration': 57.14,
 'Accountability': 57.14,
 'Business Leadership': 57.14,
 'Benefits Realization': 45.24}

In [16]:
dict(drivers_average_score_data)['Business Performance']

42.86

In [ ]:
{'Business Performance': dict(drivers_average_score_data)['Business Performance']}

{'Business Performance': 42.86}

:

In [10]:
{drivers_average_score_data[0][0]: drivers_average_score_data[0][1]}

{'Business Performance': 42.86}

In [4]:
con.sql('SELECT * FROM users').df()

   id        username                               email
0   1        john_doe                john.doe@example.com
1   2      jane_smith              jane.smith@example.com
2   3      jane_smith              jane.smith@example.com
3   4  stephanie_song        shuet.yee.song@accenture.com
4   5      emily_wong          emily.a.wong@accenture.com
5   6       yap_shyne             shyne.yap@accenture.com
6   7     aisha_yusuf           aisha.yusuf@accenture.com
7   8    danial_mirza  danial.m.bin.madrawi@accenture.com

In [5]:
duckdb.read_csv('../data/ASTAR_responses.csv').df().columns

Index(['respondent id', 'username', 'Designation', 'TGPS Grouping',
       'enb|ldr_support_system', 'enb|ldr_time_resources', 'enb|conf_lv2_ldr',
       'sfb|current_change_mgmt', 'rsb|quick_remedial',
       'llb|leads_implementation', 'llb|performance_management',
       'llb|talents_utilised', 'llb|conf_lv5_ldr', 'llb|recognised_rewarded',
       'llb|role_clarity', 'llb|accountable', 'llb|objectives_outcomes',
       'eeb|fear', 'eeb|distress', 'eeb|anger'],
      dtype='object')

In [ ]:
# for username, email in con.sql("select lower(split_part(username, '@', 1)) as username, lower(username) as email from '../data/ASTAR_responses.csv'").fetchall():
#     con.sql(f"INSERT INTO users (id, username, email) VALUES (NEXTVAL('users_id_seq'),'{username}', '{email}')")

In [15]:
con.sql(f"select * from users").df()

      id        username                           email
0      1        john_doe            john.doe@example.com
1      2      jane_smith          jane.smith@example.com
2      3      jane_smith          jane.smith@example.com
3      4  stephanie_song    shuet.yee.song@accenture.com
4      5      emily_wong      emily.a.wong@accenture.com
..   ...             ...                             ...
364  365     jerald_chua    jerald_chua@hq.a-star.edu.sg
365  366     chua_yirong    chua_yirong@hq.a-star.edu.sg
366  367   koid_wei_ling  koid_wei_ling@hq.a-star.edu.sg
367  368      spring_kan     spring_kan@hq.a-star.edu.sg
368  369          pheesc         pheesc@hq.a-star.edu.sg

[369 rows x 3 columns]

In [ ]:
for i in con.sql("select lower(split_part(username, '@', 1)) as username from '../data/ASTAR_responses.csv'").fetchnumpy()['username'].tolist():
    con.sql(f"INSERT INTO users (username) VALUES ('{i}')")

kenneth_kuan
jolin_chua
kenny_soh
connie_chan
witri_ramli
grace_lai
evita_ang
weegn
kathleen_chong
joyce_tay
dhanaraj_kumaravel
clarissa_choo
tansmj
celestina_foo
liew_wee_kiat
lim_kai_boon
chiam_mei_hui
lea_ling_nui
christy_tan
peggy_low
pauline_tan
wee_min_zhi
angie_ng
lovelle_lam
eileen_lee
garry_chung
ho_lai_ping
phurjt
jolene_cheng
ng_jing_ying
moh_yun_fen
susan_lau
ng_gim_yeow
ashley_tan
joseph_ong
bala_narayanan
chua_lay_hong
cheng_wai_man
azlinah_ahmad_said
edwin_lim
felicia_goh
ng_heng_tio
pang_shihui
soon_mei_yi
ram_sakthi
hendri_jaya
tay_chay_wah
lim_bee_sian
elissa_lim
tan_hsiao_yuen
gan_wei_xuan
jerica_tan
jasmine_yuen
yeo_li_tong
leng_chee_weng
lim_gek_lian
cw-wong
noor_nisha
dorothy_yeo
ong_hui_yong
serene_giam
yeo_yew_peng
nariyah_ismail
han_yong_ping
kristine_kow
jerome_tang
athar_ali_buang
tanhz
rachel_teo_ngi_ching
chanel_ng
kelvin_tan
jessica_tan
tan_jie_shi
wang_junfeng
julie_loke
jolene_cheah
sherlyn_wong
pouw_lih_woei
lohhpc
pauline_chua
kelly_tan
amirah_amran
md_danial_hadi
eileen_kay
lohxj
kerah
vivian_chua
calvin_zeng
chen_shuzhen
maslinda_sinin
tan_yin_xuan
jas_khew
limch
adrianne_liang
leeky
elsa_toh
eunice_heng
wee_li_lin
joshua_yap
limsl
zhuox
may_yeo
joyce_ng
vijaya_kb
wongyc
venise_lim
nicholas_fong
jeremy_woo
pselvi
shahizayati_senawi
pauline_kweck
victor_tan
jessica_jessie
joanne_chew
sebastianms
lee_miao_xuan
pavithra_prakash
alice_chua
dean_tan
rebekah_tay
bernard_tay
daniel_tan
jeslyna_chow
janice_teo
ashley_ng
lim_kah_heng
patricia_tay
chua_huey_kiow
tan_bee_keow
sarah_lim
jolene_koh
yahayaz
zong_yun
larisa_tan
vanessa_koh
santhymp
quah_soon_hong
chua_xin_yi
ong_si_wei
cally_lim
gohsk
reuben_kim
sheila_boh
sharon_ho
gina_choo
herlina
li_qingshan
sngjp
cheryl_lee_rl
jamie_low
anne_ang
sebastian_soo
tiffany_yang
chuah_tze_wen
sean_tan
ann_leong
anisah_kamis
avril_chong
kangmd
jonathan_lim
carissa_tan
aloysiusl
doris_teo
shirlyn_ng
ivy_chan
umarani_suppiah
felicia_chew
ashlyn_tan
fanny_mah
zulhilmi_ishak
karen_chin
rexford_song
jason_seah
seah_siok_har
bervyn_lee
chua_sabrina
ongwp
chia_zu_ni
andy_gue
rachel_low
sulastry_sujak
yvonne_mah
michelle_tan
adrianti_rasip
shirley_tan
chua_wei_hong
hayden_ong
joanne_ng
othmanr
tan_chong_lee
eileen_liang
lowll
jazlyn_lye
ang_bee_choo
jessie_tan
joyce_tong
lui_yoke_san
bernard_chan
ben_phua
khairul_ariffin
gabriel_tong
kenneth_chua
nurul_adilah
joyce_leong
cher_wong
ray_loh
mohdah
koh_wei_ling
melody_goh
joey_ong
jasmine_hoe
ace_luo
jasmine_chan
chu_hui_ying
tham_wai_leng
wendy_tan
syakirah_amir
wangl2
gladys_goh
elaine_ng
michelle_chew
giang_choon_chee
sheryl_chen
tracy_lim
cheryl_chew
joyce_geng
anna_lam
tanjeem
nurhafizah_zahid
jayce_lee
camellia_poh
may_toe
surin_lin
debbie_yeo
tanchy
joyce_yin
adrienne_ong
amos_goh
matthew_lian
nick_lim
josephine_ng
hazwani_begum
faustina_lim
desmond_tung
robby_mandoro
lim_kok_hua
adeline_loy
kho_siying
francis_lim
tayhm
loo_wei_yi
zhang_huiqi
gibson_wong
cheryl_pang
fiona_loh
qi_xin
ingried_ho
samuel_lee
serene_liam
lee_li_ann
chua_pei_shan
cliff_han
gabriel_tay
ang_jie_leng
regina_chen
nurul_syahidah
siti_aisyah
rachel_chen
fathin_amallia
jess_chng
leowje
lim_fui_ling
muhammad_hafiz
chris_chau
suresh_sachi
ang_wen_mei
doreen_koh
melissa_lim
loh_si_min
charmayne_goh
leo_ng
chong_wye_ming
tay_woon_yee
isabelle_chua
haffiz_hussin
desmond_ong
foo_ai_ching
tan_xiu_qin
tham_siew_pheng
joan_ng
shazwin_safril
teyc
wendy_cheong
mardhiah_safiee
may_leong
gabriel_yeong
sandy_lim
peh_chin_ghee
melissa_aw
yee_yang_hao
linda_sim
daryl_lee
brenda_lim
chua_jin_cai
lim_yann_yun
yap_ying_shin
eurica_wong
lei_tingting
goh_jing_jun
koh_jie_ying
siti_zulaiha
syafiqah_syed
stephanie_ong
cassandra_pereira
lana_lum
angeline_heng
nadirah_hanafi
angela_yeo
maggie_lee
gayatri_aruchunan
lin_kwok_chen
yap_baokun
natalie_png
jacelyn_poh
colleen_wong
chloe_ng
celina_chan
lui_vik_kee
nicole_lim
ong_hwee_ling
vanessa_goh
chung_siew_chin
marcus_ng
ernest_chua
angeline_lim
nur_asheera
michael_tai
lim_yu_bin
joanne_seah
ngay
lau_mei_fang
gracia_teo
petra_sibuea
leondra_low
bernice_tan
lim_sin_wai
vivien_tan
michelle_ng
chiong_yan_ting
chen_zijie
philip_lim
wendy_tan_kh
clara_tan
zuliana_rosali
phebe_lim
mabel_chua
jerald_chua
chua_yirong
koid_wei_ling
spring_kan
pheesc

In [25]:
con.sql(""" 
        
        with answers as (
        unpivot '../data/ASTAR_responses.csv'
            on 
            "enb|ldr_support_system", "enb|ldr_time_resources", "enb|conf_lv2_ldr",
            "sfb|current_change_mgmt", "rsb|quick_remedial",
            "llb|leads_implementation", "llb|performance_management",
            "llb|talents_utilised", "llb|conf_lv5_ldr", "llb|recognised_rewarded",
            "llb|role_clarity", "llb|accountable", "llb|objectives_outcomes",
            "eeb|fear", "eeb|distress", "eeb|anger"
        into NAME drivers VALUE scores)
        select * from answers
        """)

┌───────────────┬───────────────────────────────┬─────────────┬──────────────────────┬────────────────────────────┬────────┐
│ respondent id │           username            │ Designation │    TGPS Grouping     │          drivers           │ scores │
│     int64     │            varchar            │   varchar   │       varchar        │          varchar           │ int64  │
├───────────────┼───────────────────────────────┼─────────────┼──────────────────────┼────────────────────────────┼────────┤
│      23891377 │ KENNETH_KUAN@HQ.A-STAR.EDU.SG │ Manager     │ Corporate Group - HR │ enb|ldr_support_system     │      4 │
│      23891377 │ KENNETH_KUAN@HQ.A-STAR.EDU.SG │ Manager     │ Corporate Group - HR │ enb|ldr_time_resources     │      6 │
│      23891377 │ KENNETH_KUAN@HQ.A-STAR.EDU.SG │ Manager     │ Corporate Group - HR │ enb|conf_lv2_ldr           │      6 │
│      23891377 │ KENNETH_KUAN@HQ.A-STAR.EDU.SG │ Manager     │ Corporate Group - HR │ sfb|current_change_mgmt    │      5 │
│      23891377 │ KENNETH_KUAN@HQ.A-STAR.EDU.SG │ Manager     │ Corporate Group - HR │ rsb|quick_remedial         │      5 │
│      23891377 │ KENNETH_KUAN@HQ.A-STAR.EDU.SG │ Manager     │ Corporate Group - HR │ llb|leads_implementation   │      7 │
│      23891377 │ KENNETH_KUAN@HQ.A-STAR.EDU.SG │ Manager     │ Corporate Group - HR │ llb|performance_management │      6 │
│      23891377 │ KENNETH_KUAN@HQ.A-STAR.EDU.SG │ Manager     │ Corporate Group - HR │ llb|talents_utilised       │      5 │
│      23891377 │ KENNETH_KUAN@HQ.A-STAR.EDU.SG │ Manager     │ Corporate Group - HR │ llb|conf_lv5_ldr           │      7 │
│      23891377 │ KENNETH_KUAN@HQ.A-STAR.EDU.SG │ Manager     │ Corporate Group - HR │ llb|recognised_rewarded    │      4 │
│          ·    │            ·                  │    ·        │          ·           │            ·               │      · │
│          ·    │            ·                  │    ·        │          ·           │            ·               │      · │
│          ·    │            ·                  │    ·        │          ·           │            ·               │      · │
│      23891347 │ PHEESC@HQ.A-STAR.EDU.SG       │ Associate   │ Corporate Group - HR │ llb|performance_management │      4 │
│      23891347 │ PHEESC@HQ.A-STAR.EDU.SG       │ Associate   │ Corporate Group - HR │ llb|talents_utilised       │      4 │
│      23891347 │ PHEESC@HQ.A-STAR.EDU.SG       │ Associate   │ Corporate Group - HR │ llb|conf_lv5_ldr           │      4 │
│      23891347 │ PHEESC@HQ.A-STAR.EDU.SG       │ Associate   │ Corporate Group - HR │ llb|recognised_rewarded    │      4 │
│      23891347 │ PHEESC@HQ.A-STAR.EDU.SG       │ Associate   │ Corporate Group - HR │ llb|role_clarity           │      4 │
│      23891347 │ PHEESC@HQ.A-STAR.EDU.SG       │ Associate   │ Corporate Group - HR │ llb|accountable            │      4 │
│      23891347 │ PHEESC@HQ.A-STAR.EDU.SG       │ Associate   │ Corporate Group - HR │ llb|objectives_outcomes    │      4 │
│      23891347 │ PHEESC@HQ.A-STAR.EDU.SG       │ Associate   │ Corporate Group - HR │ eeb|fear                   │      4 │
│      23891347 │ PHEESC@HQ.A-STAR.EDU.SG       │ Associate   │ Corporate Group - HR │ eeb|distress               │      4 │
│      23891347 │ PHEESC@HQ.A-STAR.EDU.SG       │ Associate   │ Corporate Group - HR │ eeb|anger                  │      4 │
├───────────────┴───────────────────────────────┴─────────────┴──────────────────────┴────────────────────────────┴────────┤
│ 5776 rows (20 shown)                                                                                           6 columns │
└──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┘

In [38]:
answers = con.sql(""" 
        
        with answers_temp as (
        unpivot '../data/ASTAR_responses.csv'
            on 
            "enb|ldr_support_system", "enb|ldr_time_resources", "enb|conf_lv2_ldr",
            "sfb|current_change_mgmt", "rsb|quick_remedial",
            "llb|leads_implementation", "llb|performance_management",
            "llb|talents_utilised", "llb|conf_lv5_ldr", "llb|recognised_rewarded",
            "llb|role_clarity", "llb|accountable", "llb|objectives_outcomes",
            "eeb|fear", "eeb|distress", "eeb|anger"
        into NAME drivers VALUE scores)
        select u.id user_id, q.id questions_id, atemp.scores  from answers_temp atemp
            inner join users u on u.username = lower(split_part(atemp.username, '@', 1))
            inner join questions q on q.qcode = atemp.drivers
        
        ;

        """).fetchall()

In [ ]:
# for user_id, questions_id, scores in answers:
    # con.sql(f"INSERT INTO answers (user_id, questions_id, answers) VALUES ({user_id}, {questions_id}, {scores})")